export const MockData = [
    {
        id: 1,
        company: 'Google',
        position_title: 'Senior Front-End Developer',
        location: 'San Jose, CA',
        work_type: 'Contract',
        salary_range: '$180-200k',
        description: 'this is where the description for the google company goes',
        available_until: 'Dec 10',
        days_posted_ago: '2 days',
        employee_bonus: '$100',
        contact: "Jane",
        bookmarked: true,
        skills: ["Bachelor's Degree in CS or related field required",
        "1+ years of experience in a .NET or Java environment and UI technologies",
        "Strong knowledge of Object-oriented design/programming, REST, and relational databases",
        "Familiarity with a process-driven software development lifecycle",
        "Excellent analysis, design, writing, and communication skills"],
        benefits: {"Competitive salary":"A highly competitive salary that reflects your skills and contributions.",
                    "Comprehensive benefits":"Enjoy a robust benefits package, including health, dental, and vision coverage.",
                },
        level: "Director",
        onsite_or_remote: "On-site"

    },

    {
        id: 2,
        company: 'Apple',
        position_title: 'Back-end Developer',
        location: 'Cupertino, CA',
        work_type: 'Fulltime',
        salary_range: '$100-200k',
        description: 'this is where the description for the apple company goes',
        available_until: 'Dec 08',
        days_posted_ago: '5 days',
        employee_bonus: '$1000',
        contact:"Joe",
        bookmarked: false,
        skills: ["Master's Degree in CS or related field required",
        "1+ years of experience in a .NET or Java environment and UI technologies",
        "Strong knowledge of Object-oriented design/programming, REST, and relational databases",
        "Familiarity with a process-driven software development lifecycle",
        "Excellent analysis, design, writing, and communication skills"],
        benefits: {"competitive salary":"A highly competitive salary that reflects your skills and contributions.",
                    "comprehensive benefits":"Enjoy a robust benefits package, including health, dental, and vision coverage.",
                },
        level: "Entry",
        onsite_or_remote: "Remote"

    },
    {
        id: 3,
        company: 'Yahoo',
        position_title: 'Web Developer',
        location: 'USA',
        work_type: 'Remote',
        salary_range: '$80-200k',
        description: 'this is where the description for the yahoo company goes',
        available_until: 'Dec 09',
        days_posted_ago: '7 days',
        employee_bonus: '$200',
        contact:"Mary",
        bookmarked: false,
        skills: ["Doctoral's Degree in CS or related field required",
        "1+ years of experience in a .NET or Java environment and UI technologies",
        "Strong knowledge of Object-oriented design/programming, REST, and relational databases",
        "Familiarity with a process-driven software development lifecycle",
        "Excellent analysis, design, writing, and communication skills"],
        benefits: {"competitive salary":"A highly competitive salary that reflects your skills and contributions.",
                    "comprehensive benefits":"Enjoy a robust benefits package, including health, dental, and vision coverage.",
                },
        level: "Internship",
        onsite_or_remote: "Remote"

    },
    {
        id: 4,
        company: 'Amazon',
        position_title: 'Web Developer',
        location: 'USA',
        work_type: 'Remote',
        salary_range: '$80-200k',
        description: 'this is where the description for the amazon company goes',
        available_until: 'Dec 09',
        days_posted_ago: '7 days',
        employee_bonus: '$200',
        contact:"Mary",
        bookmarked: false,
        skills: ["Doctoral's Degree in CS or related field required",
        "1+ years of experience in a .NET or Java environment and UI technologies",
        "Strong knowledge of Object-oriented design/programming, REST, and relational databases",
        "Familiarity with a process-driven software development lifecycle",
        "Excellent analysis, design, writing, and communication skills"],
        benefits: {"competitive salary":"A highly competitive salary that reflects your skills and contributions.",
                    "comprehensive benefits":"Enjoy a robust benefits package, including health, dental, and vision coverage.",
                },
        level: "Mid-Senior",
        onsite_or_remote: "On-site"

    },
    {
        id: 5,
        company: 'Meta',
        position_title: 'Web Developer',
        location: 'USA',
        work_type: 'Remote',
        salary_range: '$80-200k',
        description: 'this is where the description for the Meta company goes',
        available_until: 'Dec 09',
        days_posted_ago: '7 days',
        employee_bonus: '$200',
        contact:"Mary",
        bookmarked: false,
        skills: ["Doctoral's Degree in CS or related field required",
        "1+ years of experience in a .NET or Java environment and UI technologies",
        "Strong knowledge of Object-oriented design/programming, REST, and relational databases",
        "Familiarity with a process-driven software development lifecycle",
        "Excellent analysis, design, writing, and communication skills"],
        benefits: {"competitive salary":"A highly competitive salary that reflects your skills and contributions.",
                    "comprehensive benefits":"Enjoy a robust benefits package, including health, dental, and vision coverage.",
                },
        level: "Associate",
        onsite_or_remote: "On-site"

    },
]
